import { Inter } from "next/font/google";
import "../globals.css";
import NavBar from "@/components/NavBar";
import SessionHandler from "@/components/SessionHandler";
import SideNav from "@/components/SideNav";
import SongBar from "@/components/SongBar";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DJ - U",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <SessionHandler>

      <div className={`${inter.className} max-w-screen bg-black lg:flex overflow-hidden`}>

        <div className="hidden w-[30%] xl:w-[20%] h-screen lg:flex">
          <SideNav />
        </div>

        <div className="absolute top-0 left-0 z-30 w-screen h-20 lg:hidden">
          <NavBar />
        </div>

        <div className="lg:flex-1 lg:h-screen w-screen h-[calc(100vh-5rem)] bg-[#0C0C0C] overflow-x-hidden overflow-y-scroll">

          {children}

        </div>

        <div className="absolute bottom-0 left-0 z-20 w-screen h-20">
          <SongBar />
        </div>

      </div>
    </SessionHandler>

  );
}
